### ISSUE TITLE
[Bug] the player who created the room will battle itself

### ISSUE THREAD

**Issue by sdk2016** [insthync/unity-tbrpg-realtime-arena#1]
Hi. I found a bug. 

When we create a room, it's seem the player who created the room will battle itself.

I attach some pictures to clearly describe the issue.

![gambar](https://user-images.githubusercontent.com/20059348/158033655-1b20906d-7b71-4e7d-bf9e-57f68dcf26d8.png)
![gambar](https://user-images.githubusercontent.com/20059348/158033670-bfd5404b-a412-40fb-a2d0-77add760cf94.png)
![gambar](https://user-images.githubusercontent.com/20059348/158033704-cf263eaa-6579-4b1d-a2a4-6e626b31960c.png)
![gambar](https://user-images.githubusercontent.com/20059348/158033728-05b0ffad-0df2-4d31-99ba-fd6eaccc9eb2.png)
![gambar](https://user-images.githubusercontent.com/20059348/158033749-bc31d0f4-9ae0-4f85-8435-71b6a716b3ff.png)

**Comment by insthync** [comment]
I will check it

**Comment by sdk2016** [comment]
Thank you. I hope to get good news from you soon.

**Comment by insthync** [comment]
Fixed, you have to pull latest commit :)

**Comment by sdk2016** [comment]
Sorry, but the latest commit was on  Feb 1, 2022


![Screenshot 2022-03-22 145914](https://user-images.githubusercontent.com/20059348/159425424-d67f3663-f52e-4286-a03c-bcc1f1fb7211.jpg)

**Comment by sdk2016** [comment]
I'm sorry. Do you mean to pull this one: https://github.com/insthync/tbrpg-realtime-arena-server

**Comment by sdk2016** [comment]
Well done. Everything is fine now. Thank you very much :)
